services:
  - type: web
    name: portfolio
    env: python
    plan: free
    runtime: python-3.10.13  # 🔥 this is the key line
    branch: main  # change if you're using a different branch
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn portfolio.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY
        value: z9-2Lz_@7GV`u5FW#.U3mT!Wh^C#cLHnN%eT9^-N!s`TgA^eWc
      - key: DEBUG
        value: false
